### ISSUE TITLE
Recording: User list search user box shifts up.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#1039]
During recording play, when camera turned off. the search user box shifts up.

![Screenshot from 2019-06-05 14-53-28](https://user-images.githubusercontent.com/36185596/58945546-afc63e00-87a1-11e9-865a-d68bd9903513.png)

**Comment by Rohitsharma2019** [comment]
fixed

**Comment by meevm** [comment]
Not yet fixed. Error still exist
![Screenshot from 2019-06-25 14-41-50](https://user-images.githubusercontent.com/12167050/60086419-aacd2c80-9758-11e9-979c-6af16a4f2326.png)

**Comment by bogatisuman** [comment]
Please  check if still exists the problem, close the ticket if it's fixed.

**Comment by ypshukla** [comment]
Not reproduced.
