### ISSUE TITLE
Text Editor: Scroll bar doesn't appear for a high resolution image.

### ISSUE THREAD

**Issue by ypshukla** [congrea/virtualclass#916]
If teacher upload a high resolution image in text editor & student is on low resolution window (1024x768). The scroll bar doesn't appear at student side untill maximize and minimize the window.

After upload the image:
![screenshot from 2018-12-19 11-41-39](https://user-images.githubusercontent.com/36185596/50202234-5ac57580-0383-11e9-9213-df0574681b7a.png)

After maximize & minimize:
![screenshot from 2018-12-19 11-41-48](https://user-images.githubusercontent.com/36185596/50202244-62851a00-0383-11e9-9c5e-7bd6048baa8e.png)

**Comment by uditbh** [comment]
Resolved

**Comment by ypshukla** [comment]
Horizontal scroll still not appearing  with maximize and minimize.

**Comment by Sudhanshu0044** [comment]
Reproduced with same steps

**Comment by bogatisuman** [comment]
Fix at https://github.com/bogatisuman/virtualclass/commit/7eb1f54ccef1e010a1fd45f862648d22c6ec059e
